// The expanded taxonomy: sub-styles within each bike type, and the freak bikes
// this tool can't model. A style holds ONLY what differs from its family; the
// rest comes from the family (see profile.ts). Every number here is my estimate
// from general knowledge, flagged as such, and meant to be replaced by reference
// charts. The example frame for a style is fitted to the middle of its ranges.
import type { InfoStyle, StyleProfile } from "./category-types"
import type { BikeType } from "./types"

const EST = "Estimates from general knowledge. To be replaced with reference charts."
const r = (low: number, high: number) => ({ low, high })

export const STYLES: StyleProfile[] = [
  // ---- Road
  {
    id: "race",
    family: "road",
    label: "Race",
    tagline: "Low, light and in a hurry.",
    forWhat: "Road racing and fast group rides. The sharpest handling and the lowest, most aerodynamic position of the road bikes.",
    different: ["A steeper head angle and a shorter wheelbase than the general road bike.", "A lower, longer position: more reach for its stack.", "Short chainstays for a quick, stiff rear end."],
    ranges: { headTubeAngle: r(72.5, 74.5), seatTubeAngle: r(73, 75.5), trail: r(54, 62), chainstayLength: r(405, 415), wheelbase: r(965, 1000) },
    positionRange: r(1.33, 1.45),
    wheel: { rimDiameter: 622, tireSection: 25 },
    reference: EST,
  },
  {
    id: "endurance",
    family: "road",
    label: "Endurance",
    tagline: "Race manners, all-day comfort.",
    forWhat: "Long days on pavement. A taller, calmer road bike with room for wider tires.",
    different: ["A slacker head angle and a longer wheelbase for a steadier ride.", "A taller, shorter position that's easier on the back.", "Longer chainstays with room for wider tires."],
    ranges: { headTubeAngle: r(71, 73), seatTubeAngle: r(72, 74), trail: r(55, 68), chainstayLength: r(415, 430), wheelbase: r(990, 1030) },
    positionRange: r(1.5, 1.65),
    wheel: { rimDiameter: 622, tireSection: 30 },
    reference: EST,
  },
  {
    id: "crit",
    family: "road",
    label: "Criterium",
    tagline: "Steep, short and sharp for tight corners and sprints.",
    forWhat: "Short, fast races on tight courses. The twitchiest road bike, built for hard cornering and quick accelerations.",
    different: ["The steepest road angles and a very short wheelbase.", "A lower bottom bracket than other race bikes would use, with pedal clearance to match.", "The most stretched-out position."],
    ranges: { headTubeAngle: r(73, 75), seatTubeAngle: r(73.5, 76), bbDrop: r(62, 72), trail: r(52, 60), chainstayLength: r(400, 412), wheelbase: r(960, 985) },
    positionRange: r(1.3, 1.42),
    wheel: { rimDiameter: 622, tireSection: 25 },
    reference: EST,
  },

  // ---- Gravel
  {
    id: "cross",
    family: "gravel",
    label: "Cyclocross",
    tagline: "Short, high and built to be shouldered through the mud.",
    forWhat: "Cyclocross racing: laps of grass, mud, barriers and stairs. A short, lively bike with a high bottom bracket and room for mud.",
    different: ["A higher bottom bracket and a shorter wheelbase than other gravel bikes.", "Narrower tires, as racing rules limit them.", "Steeper angles for quick handling."],
    ranges: { headTubeAngle: r(71, 73), seatTubeAngle: r(72.5, 74.5), bbDrop: r(55, 66), trail: r(55, 65), chainstayLength: r(420, 430), wheelbase: r(1000, 1030) },
    positionRange: r(1.4, 1.5),
    wheel: { rimDiameter: 622, tireSection: 34 },
    reference: EST,
  },
  {
    id: "gravel-race",
    family: "gravel",
    label: "Gravel race",
    tagline: "Fast on loose ground.",
    forWhat: "Racing and fast riding on gravel. A road-fast bike made stable enough for loose surfaces.",
    different: ["Road-like angles with a little more trail and wheelbase.", "A position close to a road bike's, a bit more upright."],
    ranges: { headTubeAngle: r(70.5, 72.5), trail: r(60, 72), chainstayLength: r(425, 435), wheelbase: r(1025, 1055) },
    positionRange: r(1.4, 1.5),
    wheel: { rimDiameter: 622, tireSection: 40 },
    reference: EST,
  },
  {
    id: "adventure",
    family: "gravel",
    label: "Adventure and bikepacking",
    tagline: "Long, stable and made to carry bags.",
    forWhat: "Big days and multi-day trips with luggage. The slackest, longest gravel bike, with plenty of room and mounts.",
    different: ["A slacker head angle and a longer wheelbase for stability with a load.", "Longer chainstays for wide tires and heel clearance.", "A taller, more upright position."],
    ranges: { headTubeAngle: r(69.5, 71.5), seatTubeAngle: r(71.5, 73.5), bbDrop: r(62, 75), trail: r(65, 85), chainstayLength: r(430, 450), wheelbase: r(1050, 1100) },
    positionRange: r(1.45, 1.6),
    wheel: { rimDiameter: 622, tireSection: 45 },
    reference: EST,
  },
  {
    id: "all-road",
    family: "gravel",
    label: "All-road",
    tagline: "One bike for pavement, dirt and everything between.",
    forWhat: "A do-it-all steel-style bike for commuting, touring and rough roads. It sits in the middle of the gravel family.",
    different: ["No extremes: it uses the general gravel numbers.", "Often built to take racks, fenders and a range of tire sizes."],
    reference: EST,
  },

  // ---- Mountain
  {
    id: "xc",
    family: "mountain",
    label: "Cross-country",
    tagline: "Light, quick and made for climbing and racing.",
    forWhat: "Racing and fast riding on mostly smooth singletrack. The steepest and shortest of the mountain bikes, built to climb and accelerate.",
    different: ["A steeper head angle, about 66 to 70°, and less trail.", "A shorter wheelbase than the other mountain styles.", "A low, long position for climbing and speed."],
    ranges: { headTubeAngle: r(66, 70), seatTubeAngle: r(72, 75.5), bbDrop: r(30, 45), trail: r(90, 112), chainstayLength: r(425, 440), wheelbase: r(1080, 1140) },
    positionRange: r(1.345, 1.495),
    wheel: { rimDiameter: 622, tireSection: 55 },
    forkAxleToCrown: 510,
    reference: EST,
  },
  {
    id: "trail",
    family: "mountain",
    label: "Trail",
    tagline: "The do-it-all of mountain biking.",
    forWhat: "General trail riding, with climbs and descents in about equal measure. A balance of the quick and the stable.",
    different: ["A slacker head angle than cross-country, about 64.5 to 67°.", "A longer wheelbase for confidence on descents."],
    ranges: { headTubeAngle: r(64.5, 67), seatTubeAngle: r(71.5, 75), bbDrop: r(30, 45), trail: r(105, 125), chainstayLength: r(430, 445), wheelbase: r(1130, 1180) },
    positionRange: r(1.33, 1.48),
    wheel: { rimDiameter: 622, tireSection: 60 },
    forkAxleToCrown: 530,
    reference: EST,
  },
  {
    id: "all-mountain",
    family: "mountain",
    label: "All-mountain",
    tagline: "Climbs all day and goes down like it means it.",
    forWhat: "Big mountain days with long climbs and rough descents. Slacker and longer than trail, still pedal-friendly.",
    different: ["A slack head angle, about 64 to 66°, and plenty of trail.", "A long wheelbase for stability on rough descents."],
    ranges: { headTubeAngle: r(64, 66), seatTubeAngle: r(71, 74.5), bbDrop: r(30, 42), trail: r(112, 130), chainstayLength: r(430, 445), wheelbase: r(1150, 1200) },
    positionRange: r(1.32, 1.47),
    wheel: { rimDiameter: 622, tireSection: 60 },
    forkAxleToCrown: 540,
    reference: EST,
  },
  {
    id: "enduro",
    family: "mountain",
    label: "Enduro",
    tagline: "Race the descents, pedal up to them.",
    forWhat: "Enduro racing and aggressive riding: timed descents with pedaled climbs between. Long, slack and low.",
    different: ["A very slack head angle, about 63 to 65.5°.", "A long wheelbase and long reach.", "Built for speed on steep, rough ground over efficiency on the climbs."],
    ranges: { headTubeAngle: r(63, 65.5), seatTubeAngle: r(70, 74), bbDrop: r(30, 42), trail: r(115, 135), chainstayLength: r(430, 450), wheelbase: r(1180, 1250) },
    positionRange: r(1.28, 1.43),
    wheel: { rimDiameter: 622, tireSection: 60 },
    forkAxleToCrown: 555,
    reference: EST,
  },
  {
    id: "downhill",
    family: "mountain",
    label: "Downhill",
    tagline: "Gravity does the work. The bike just has to stay on the ground.",
    forWhat: "Racing and riding straight down steep, rough terrain, usually by lift or shuttle. The longest, slackest bikes of all.",
    different: ["The slackest head angle, about 62 to 64.5°, and the longest wheelbase.", "Not built for pedaling uphill.", "Very long travel, so the numbers change a lot as the suspension moves."],
    ranges: { headTubeAngle: r(62, 64.5), seatTubeAngle: r(66, 72), bbDrop: r(25, 40), trail: r(120, 145), chainstayLength: r(430, 445), wheelbase: r(1220, 1300) },
    positionRange: r(1.22, 1.36),
    wheel: { rimDiameter: 584, tireSection: 62 },
    crankLength: 165,
    forkAxleToCrown: 575,
    reference: EST,
  },
  {
    id: "dirt-jump",
    family: "mountain",
    label: "Dirt jump",
    tagline: "Small, stiff and made to leave the ground on purpose.",
    forWhat: "Dirt jumps, pump tracks and slopestyle. A short, compact bike with small wheels, built for air time and quick control.",
    different: ["A much shorter wheelbase and very short chainstays.", "A steeper head angle than the trail bikes, with a high, compact stance.", "Smaller wheels and a low seat, or none."],
    ranges: { headTubeAngle: r(68, 71), seatTubeAngle: r(70, 74), bbDrop: r(15, 30), trail: r(80, 100), chainstayLength: r(385, 400), wheelbase: r(1010, 1070) },
    positionRange: r(1.2, 1.35),
    wheel: { rimDiameter: 559, tireSection: 50 },
    crankLength: 165,
    grade: { reachStep: 12, stackStep: 8, seatTubeStep: 15 },
    forkAxleToCrown: 445,
    reference: EST,
  },
  {
    id: "fat",
    family: "mountain",
    label: "Fat bike",
    tagline: "Snow, sand, and a very large tire.",
    forWhat: "Riding on snow, sand and soft ground, on very wide tires. A mountain bike with extra room and a big wheel.",
    different: ["Very wide tires, so a much bigger wheel for its rim size.", "A longer rear end to fit the tire and the wide hub.", "Wide cranks and rear spacing."],
    ranges: { headTubeAngle: r(67, 70), seatTubeAngle: r(71, 74.5), bbDrop: r(20, 40), trail: r(90, 112), chainstayLength: r(440, 460), wheelbase: r(1100, 1150) },
    positionRange: r(1.3, 1.45),
    wheel: { rimDiameter: 559, tireSection: 92 },
    forkAxleToCrown: 490,
    reference: EST,
  },

  // ---- Touring
  {
    id: "expedition",
    family: "touring",
    label: "Expedition",
    tagline: "Built to go a very long way with all your stuff.",
    forWhat: "Long loaded trips, often far from help. A long, stable, tough bike with room and mounts for everything.",
    different: ["The longest chainstays and wheelbase of the touring bikes, for stability and heel room.", "A slightly slacker head angle for steadiness under load.", "A tall, upright position."],
    ranges: { headTubeAngle: r(70.5, 72.5), seatTubeAngle: r(72, 73.5), trail: r(55, 70), chainstayLength: r(455, 480), wheelbase: r(1080, 1140) },
    positionRange: r(1.5, 1.7),
    reference: EST,
  },
  {
    id: "randonneur",
    family: "touring",
    label: "Randonneur",
    tagline: "Fast, light touring, with steering tuned for a front bag.",
    forWhat: "Fast, long-distance riding with light luggage, often carried on the front. A lively touring bike with low-trail steering.",
    different: ["Low trail, so the steering stays light and steady with a front bag.", "A shorter, livelier frame than an expedition bike.", "Often smaller, wider tires on a 650b wheel."],
    ranges: { headTubeAngle: r(72, 73.5), seatTubeAngle: r(72.5, 74), trail: r(30, 50), chainstayLength: r(420, 445), wheelbase: r(1020, 1070) },
    positionRange: r(1.45, 1.6),
    wheel: { rimDiameter: 584, tireSection: 40 },
    forkAxleToCrown: 375,
    reference: EST,
  },
  {
    id: "commuter",
    family: "touring",
    label: "Commuter and city",
    tagline: "Upright, practical and happy to get dirty.",
    forWhat: "Getting around town every day. An upright, stable bike with fenders, a rack and tires that shrug off potholes.",
    different: ["The most upright position of the touring bikes.", "Steady, predictable steering for traffic and a load of groceries.", "A shorter rear end than expedition bikes."],
    ranges: { headTubeAngle: r(71, 72.5), seatTubeAngle: r(72.5, 74), trail: r(55, 70), chainstayLength: r(430, 455), wheelbase: r(1020, 1070) },
    positionRange: r(1.55, 1.75),
    wheel: { rimDiameter: 622, tireSection: 32 },
    forkAxleToCrown: 385,
    reference: EST,
  },

  // ---- Track
  {
    id: "sprint",
    family: "track",
    label: "Sprint and keirin",
    tagline: "As short and steep as it gets.",
    forWhat: "Sprint and keirin racing on the velodrome. The shortest, steepest and stiffest bike here, built to turn tightly at speed on a banked track.",
    different: ["The steepest head angle and the shortest wheelbase.", "Very short chainstays, for stiffness.", "A high bottom bracket for the banking."],
    ranges: { headTubeAngle: r(73.5, 75.5), seatTubeAngle: r(74, 76.5), bbDrop: r(35, 50), trail: r(55, 62), chainstayLength: r(395, 408), wheelbase: r(935, 975) },
    positionRange: r(1.28, 1.4),
    reference: EST,
  },
  {
    id: "pursuit",
    family: "track",
    label: "Endurance and pursuit",
    tagline: "Fast over a long, steady lap.",
    forWhat: "Pursuit and endurance events on the velodrome. A little longer and calmer than a sprint bike, with a low, aerodynamic position.",
    different: ["A slightly slacker head angle and longer wheelbase than a sprint bike.", "A low, long position for aerodynamics."],
    ranges: { headTubeAngle: r(73, 74.5), seatTubeAngle: r(74, 76.5), bbDrop: r(40, 55), trail: r(55, 62), chainstayLength: r(400, 412), wheelbase: r(960, 995) },
    positionRange: r(1.25, 1.4),
    reference: EST,
  },
  {
    id: "street",
    family: "track",
    label: "Street and fixed gear",
    tagline: "Track looks, ridden in traffic.",
    forWhat: "Riding a fixed gear or single speed around town. A track-style frame, relaxed a little for the road, often with brake mounts.",
    different: ["A lower bottom bracket than a track bike, since there's no banking to clear.", "Slightly slacker angles and more room for tires and brakes.", "A bit more upright than a race track bike."],
    ranges: { headTubeAngle: r(72, 74), seatTubeAngle: r(72.5, 75), bbDrop: r(55, 70), trail: r(55, 66), chainstayLength: r(405, 420), wheelbase: r(960, 1010) },
    positionRange: r(1.35, 1.5),
    wheel: { rimDiameter: 622, tireSection: 28 },
    reference: EST,
  },

  // ---- Bruiser
  {
    id: "klunker",
    family: "bruiser",
    label: "Klunker",
    tagline: "The original mountain bike: a heavy old cruiser, pointed downhill.",
    forWhat: "A ballooned-tire cruiser built or modified to ride rough hills, the way the first mountain bikers did. Heavy, simple and fun.",
    different: ["A slack-ish head angle and a long rear end for stability.", "A high bottom bracket for clearance on dirt.", "Wide, sweeping bars and fat tires."],
    ranges: { headTubeAngle: r(67, 70), seatTubeAngle: r(69, 72), bbDrop: r(15, 35), trail: r(65, 90), chainstayLength: r(440, 470), wheelbase: r(1080, 1140) },
    positionRange: r(1.2, 1.35),
    wheel: { rimDiameter: 559, tireSection: 52 },
    forkAxleToCrown: 395,
    reference: EST,
  },
  {
    id: "basket-bike",
    family: "bruiser",
    label: "Basket bike",
    tagline: "A road-bike frame with flat bars and a basket on the front.",
    forWhat: "Errands, the market and the ride to a friend's. Road-bike bones with flat bars, easy angles, a taller front end, and room for a basket and fenders.",
    different: ["Road-bike angles and wheel size, relaxed a little and with flat bars.", "A taller front end than a road bike, so you sit up.", "Lower trail steadies the steering with a loaded front basket."],
    ranges: { headTubeAngle: r(70.5, 73), seatTubeAngle: r(71.5, 74), bbDrop: r(60, 78), trail: r(50, 68), chainstayLength: r(425, 455), wheelbase: r(1020, 1085) },
    positionRange: r(1.25, 1.42),
    wheel: { rimDiameter: 622, tireSection: 38 },
    forkAxleToCrown: 365,
    rangeWhy: {
      headTubeAngle: "About 70.5 to 73°: a little more relaxed than a road bike, steady with a basket on the front.",
      seatTubeAngle: "About 71.5 to 74°, close to a road bike, so pedaling feels familiar.",
      trail: "50 to 68 mm. Less trail than a typical road bike keeps the steering from flopping when the basket is loaded.",
      wheelbase: "About 1020 to 1085 mm for a medium: room for a basket and fenders without feeling long.",
      chainstayLength: "425 to 455 mm leaves space for fenders and a rear rack.",
      bbDrop: "60 to 78 mm keeps the bottom bracket low, so it is easy to step on and off.",
      position: "A taller front end for flat bars, so you sit up and see the traffic.",
    },
    reference: EST,
  },
  {
    id: "beach-cruiser",
    family: "bruiser",
    label: "Beach cruiser",
    tagline: "Swept bars, big tires, zero hurry.",
    forWhat: "Relaxed riding on flat ground, along the beach or around the neighborhood. Very relaxed and very comfortable.",
    different: ["The slackest, longest and lowest of the bruisers.", "A long wheelbase and a very upright position.", "A very low bottom bracket."],
    ranges: { headTubeAngle: r(64, 68), seatTubeAngle: r(67, 71), bbDrop: r(55, 80), trail: r(60, 85), chainstayLength: r(460, 490), wheelbase: r(1150, 1250) },
    positionRange: r(1.25, 1.45),
    wheel: { rimDiameter: 559, tireSection: 52 },
    forkAxleToCrown: 395,
    reference: EST,
  },
  {
    id: "retro-mtb",
    family: "bruiser",
    label: "Retro mountain bike",
    tagline: "A rigid 1990s trail bike, brought back for fun.",
    forWhat: "A rigid steel mountain bike with early-1990s geometry: steeper and shorter than today's, and a lot of fun.",
    different: ["A steeper head angle, about 69 to 71.5°, than today's mountain bikes.", "A shorter wheelbase, so quicker handling.", "A high bottom bracket."],
    ranges: { headTubeAngle: r(69, 71.5), seatTubeAngle: r(71, 73.5), bbDrop: r(15, 35), trail: r(70, 90), chainstayLength: r(430, 450), wheelbase: r(1050, 1100) },
    positionRange: r(1.22, 1.36),
    wheel: { rimDiameter: 559, tireSection: 50 },
    forkAxleToCrown: 400,
    reference: EST,
  },
  {
    id: "big-bmx",
    family: "bruiser",
    label: "BMX cruiser",
    tagline: "A big BMX, for grown-ups, with a bit of swagger.",
    forWhat: "A larger-wheeled BMX-style bike for cruising around. Short and playful, with a relaxed riding position.",
    different: ["Smaller wheels, 20 to 24 inch, so a shorter wheelbase.", "Short chainstays for a lively, punchy feel.", "A more upright position than a race BMX."],
    ranges: { headTubeAngle: r(71, 74), seatTubeAngle: r(70, 73), bbDrop: r(0, 25), trail: r(55, 75), chainstayLength: r(360, 400), wheelbase: r(960, 1050) },
    positionRange: r(1.15, 1.3),
    wheel: { rimDiameter: 507, tireSection: 45 },
    crankLength: 165,
    forkAxleToCrown: 370,
    reference: EST,
  },
]

/** Freak bikes: great, weird and out of this tool's reach for now. */
export const FREAK_STYLES: InfoStyle[] = [
  {
    id: "chopper",
    label: "Chopper",
    tagline: "A raked-out fork, a long wheelbase and zero apologies.",
    forWhat: "Long, low and slack, with a very raked fork and a tall sissy-bar seat. All about looking cool at a very relaxed pace.",
    different: ["An extremely slack head angle, often 55 to 62°.", "A very long fork and a long wheelbase.", "Steering that's wild and heavy, so go slowly."],
    whyNot: "The tool can draw it, but there's no typical range to compare against, and an extreme fork rake needs care. It could be added as its own loose type.",
    possibleLater: true,
  },
  {
    id: "longtail",
    label: "Longtail cargo",
    tagline: "A bike with a very long back end and room for the whole family.",
    forWhat: "Carrying kids, groceries or half the house. An extended rear triangle holds a big rack or passenger seats.",
    different: ["Extra-long chainstays, often 600 mm or more.", "A very long wheelbase.", "Frame strength matters more than anything here."],
    whyNot: "The tool can draw the long rear end, but it doesn't model the rear rack, the load or the extra strength the frame needs. It could be added later.",
    possibleLater: true,
  },
  {
    id: "tall-bike",
    label: "Tall bike",
    tagline: "Two frames, stacked. You're up there with the traffic lights.",
    forWhat: "A bike with a second frame welded on top, so the rider sits very high. Pure showmanship.",
    different: ["The seat is far above the pedals, with a separate frame and chain.", "Mounting and stopping are an event."],
    whyNot: "It's two stacked frames and two chains, which this tool's single side-view frame can't represent.",
    possibleLater: false,
  },
  {
    id: "tandem",
    label: "Tandem",
    tagline: "Two riders, one bike, and a lot of trust.",
    forWhat: "Riding as a pair, with a captain in front and a stoker behind. Fast and fun when you're in sync.",
    different: ["A very long wheelbase and two seat tubes.", "The frame is much more heavily stressed.", "Needs extra tubes and a synchronized drivetrain."],
    whyNot: "It has two seat tubes, two sets of positions and a different frame structure, which this tool doesn't model.",
    possibleLater: false,
  },
  {
    id: "recumbent",
    label: "Recumbent",
    tagline: "Lie back and pedal. Comfortable, low and very noticeable.",
    forWhat: "Riding in a laid-back seat with the pedals out front. Comfortable and aerodynamic, and a head-turner.",
    different: ["No seat tube: the rider sits low in a laid-back seat.", "The geometry is measured in a completely different way."],
    whyNot: "The whole frame layout is different. There's no seat tube, and the numbers mean different things, so the diamond-frame tool doesn't apply.",
    possibleLater: false,
  },
  {
    id: "folding",
    label: "Folding bike",
    tagline: "Small wheels, big cleverness.",
    forWhat: "A bike that folds up for trains, cars and tiny apartments. Small wheels and a hinge or two.",
    different: ["Small wheels, 16 to 20 inch, with a very short wheelbase.", "Hinges and a telescoping seat post and stem.", "Handling that's quick and a little nervous."],
    whyNot: "The hinges and the telescoping parts are the point, and this tool doesn't model them. It's a lovely idea for later.",
    possibleLater: false,
  },
]

export const stylesOf = (family: BikeType): StyleProfile[] => STYLES.filter((s) => s.family === family)

export const styleOf = (family: BikeType, id: string | null | undefined): StyleProfile | null =>
  id ? (STYLES.find((s) => s.family === family && s.id === id) ?? null) : null

export const isStyleOf = (family: BikeType, id: string): boolean => styleOf(family, id) !== null
